[2025-02-01T00:56:18.374+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:56:09.876322+00:00 [queued]>
[2025-02-01T00:56:18.378+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:56:09.876322+00:00 [queued]>
[2025-02-01T00:56:18.378+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-02-01T00:56:18.385+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_ndjson_to_bigquery> on 2025-02-01 00:56:09.876322+00:00
[2025-02-01T00:56:18.395+0000] {standard_task_runner.py:57} INFO - Started process 2029 to run task
[2025-02-01T00:56:18.400+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_gcs_to_bigquery', 'load_ndjson_to_bigquery', 'manual__2025-02-01T00:56:09.876322+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_test_dag.py', '--cfg-path', '/tmp/tmpzwsmk2i6']
[2025-02-01T00:56:18.404+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask load_ndjson_to_bigquery
[2025-02-01T00:56:18.433+0000] {task_command.py:410} INFO - Running <TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:56:09.876322+00:00 [running]> on host 3f33197bb456
[2025-02-01T00:56:18.481+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='load_ndjson_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:56:09.876322+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T00:56:09.876322+00:00'
[2025-02-01T00:56:18.487+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T00:56:19.055+0000] {logging_mixin.py:150} INFO - [INFO] flight_lowest_prices 테이블이 존재하지 않음, 생성 중...
[2025-02-01T00:56:19.071+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:138 AirflowProviderDeprecationWarning: This method will be deprecated. Please use `BigQueryHook.get_client` method
[2025-02-01T00:56:19.080+0000] {sql.py:375} INFO - Running statement: 
            CREATE TABLE `ticketchecker-449405.ticket_checker.flight_lowest_prices` (
                date STRING,
                airline STRING,
                departure_airport STRING,
                arrival_airport STRING,
                departure_time STRING,
                arrival_time STRING,
                lowest_price_adult INTEGER,
                seat_class STRING,
                currency STRING,
                carbon_emission FLOAT64,  -- ✅ 변경
                errors ARRAY<STRING>
            )
        , parameters: None
[2025-02-01T00:56:19.081+0000] {logging_mixin.py:150} WARNING - /home/***/.local/lib/python3.7/site-packages/***/providers/google/cloud/hooks/bigquery.py:2118 AirflowProviderDeprecationWarning: This method is deprecated. Please use `BigQueryHook.insert_job` method.
[2025-02-01T00:56:19.083+0000] {bigquery.py:1592} INFO - Inserting job ***_1738371379082463_c15d6fdc6562385425cb5cb063c86033
[2025-02-01T00:56:20.751+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/bigquery_test_dag.py", line 94, in load_ndjson_to_bigquery
    """)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 349, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 380, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2765, in execute
    query_results = self._get_query_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 2888, in _get_query_result
    .execute(num_retries=self.num_retries)
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/ticketchecker-449405/queries/airflow_1738371379082463_c15d6fdc6562385425cb5cb063c86033?alt=json returned "Not found: Job ticketchecker-449405:airflow_1738371379082463_c15d6fdc6562385425cb5cb063c86033". Details: "[{'message': 'Not found: Job ticketchecker-449405:airflow_1738371379082463_c15d6fdc6562385425cb5cb063c86033', 'domain': 'global', 'reason': 'notFound'}]">
[2025-02-01T00:56:20.776+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=test_gcs_to_bigquery, task_id=load_ndjson_to_bigquery, execution_date=20250201T005609, start_date=20250201T005618, end_date=20250201T005620
[2025-02-01T00:56:20.788+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 80 for task load_ndjson_to_bigquery (<HttpError 404 when requesting https://bigquery.googleapis.com/bigquery/v2/projects/ticketchecker-449405/queries/airflow_1738371379082463_c15d6fdc6562385425cb5cb063c86033?alt=json returned "Not found: Job ticketchecker-449405:airflow_1738371379082463_c15d6fdc6562385425cb5cb063c86033". Details: "[{'message': 'Not found: Job ticketchecker-449405:airflow_1738371379082463_c15d6fdc6562385425cb5cb063c86033', 'domain': 'global', 'reason': 'notFound'}]">; 2029)
[2025-02-01T00:56:20.815+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-01T00:56:20.841+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
