[2025-02-01T01:01:22.580+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:56:09.876322+00:00 [queued]>
[2025-02-01T01:01:22.587+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:56:09.876322+00:00 [queued]>
[2025-02-01T01:01:22.587+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2025-02-01T01:01:22.597+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_ndjson_to_bigquery> on 2025-02-01 00:56:09.876322+00:00
[2025-02-01T01:01:22.602+0000] {standard_task_runner.py:57} INFO - Started process 2265 to run task
[2025-02-01T01:01:22.606+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'test_gcs_to_bigquery', 'load_ndjson_to_bigquery', 'manual__2025-02-01T00:56:09.876322+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_test_dag.py', '--cfg-path', '/tmp/tmpr77k_owe']
[2025-02-01T01:01:22.608+0000] {standard_task_runner.py:85} INFO - Job 86: Subtask load_ndjson_to_bigquery
[2025-02-01T01:01:22.640+0000] {task_command.py:410} INFO - Running <TaskInstance: test_gcs_to_bigquery.load_ndjson_to_bigquery manual__2025-02-01T00:56:09.876322+00:00 [running]> on host 3f33197bb456
[2025-02-01T01:01:22.701+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_gcs_to_bigquery' AIRFLOW_CTX_TASK_ID='load_ndjson_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:56:09.876322+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T00:56:09.876322+00:00'
[2025-02-01T01:01:22.708+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:01:22.713+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T01:01:24.836+0000] {logging_mixin.py:150} INFO - [ERROR] GCS JSON 데이터 변환 실패: Extra data: line 2 column 1 (char 1353)
[2025-02-01T01:01:24.838+0000] {python.py:183} INFO - Done. Returned value was: None
[2025-02-01T01:01:24.864+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=test_gcs_to_bigquery, task_id=load_ndjson_to_bigquery, execution_date=20250201T005609, start_date=20250201T010122, end_date=20250201T010124
[2025-02-01T01:01:24.880+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-02-01T01:01:24.902+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
