[2025-02-01T02:07:36.565+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:07:31.126955+00:00 [queued]>
[2025-02-01T02:07:36.569+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:07:31.126955+00:00 [queued]>
[2025-02-01T02:07:36.570+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-02-01T02:07:36.587+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): upload_to_bigquery> on 2025-02-01 02:07:31.126955+00:00
[2025-02-01T02:07:36.591+0000] {standard_task_runner.py:57} INFO - Started process 1629 to run task
[2025-02-01T02:07:36.594+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs_to_bigquery_dag', 'upload_to_bigquery', 'manual__2025-02-01T02:07:31.126955+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/json_to_bigquery.py', '--cfg-path', '/tmp/tmpp_ks_0u9']
[2025-02-01T02:07:36.597+0000] {standard_task_runner.py:85} INFO - Job 121: Subtask upload_to_bigquery
[2025-02-01T02:07:36.630+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs_to_bigquery_dag.upload_to_bigquery manual__2025-02-01T02:07:31.126955+00:00 [running]> on host 3f33197bb456
[2025-02-01T02:07:36.680+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs_to_bigquery_dag' AIRFLOW_CTX_TASK_ID='upload_to_bigquery' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T02:07:31.126955+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T02:07:31.126955+00:00'
[2025-02-01T02:07:36.691+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2025-02-01T02:07:36.717+0000] {logging_mixin.py:150} INFO - üü¢ BigQueryÏóê ÏóÖÎ°úÎìúÌï† Îç∞Ïù¥ÌÑ∞: [{'date': '20250201', 'airline': '', 'flight_number': '', 'departure_airport': '', 'arrival_airport': '', 'departure_time': '', 'arrival_time': '', 'carbon_emission': 0.0}]
[2025-02-01T02:07:36.718+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/json_to_bigquery.py", line 131, in upload_to_bigquery
    bigquery_hook.insert_rows_json(
AttributeError: 'BigQueryHook' object has no attribute 'insert_rows_json'
[2025-02-01T02:07:36.726+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=gcs_to_bigquery_dag, task_id=upload_to_bigquery, execution_date=20250201T020731, start_date=20250201T020736, end_date=20250201T020736
[2025-02-01T02:07:36.734+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 121 for task upload_to_bigquery ('BigQueryHook' object has no attribute 'insert_rows_json'; 1629)
[2025-02-01T02:07:36.780+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-01T02:07:36.796+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
